### ISSUE TITLE
[Bug]: edge功能不全

### ISSUE THREAD

**Issue by ning0818** [inwinter04/win11React_CN#21]
### 发生了什么?

edge功能不全

### 如何复现这个问题
![image](https://user-images.githubusercontent.com/117955401/225794617-85023285-c82e-4a97-94f6-3a046a8e7192.png)

![image](https://user-images.githubusercontent.com/117955401/225794362-2f518e6d-1c32-4e49-b15c-6da460668dcd.png)

![image](https://user-images.githubusercontent.com/117955401/225794400-437e6a59-8d0a-4550-849d-29e9cf2158a2.png)

### 您在什么浏览器上遇到这个问题?

Microsoft Edge

**Comment by inwinter04** [comment]
感谢你发来的Issue。本项目旨在使用 React、CSS 和 JavaScript 等标准 Web 技术在 Web 上复制 Windows 11 桌面体验。所以，这并不是一个真正的Edge浏览器，故并没有配备游戏彩蛋。
当然，这可以作为接下来开发的一个目标。👾

**Comment by ning0818** [comment]
> 感谢你发来的Issue。本项目旨在使用 React、CSS 和 JavaScript 等标准 Web 技术在 Web 上复制 Windows 11 桌面体验。所以，这并不是一个真正的Edge浏览器，故并没有配备游戏彩蛋。 当然，这可以作为接下来开发的一个目标。👾

回复真快
