### ISSUE TITLE
[Bug]: 不能访问！！！

### ISSUE THREAD

**Issue by NebulaTechs** [inwinter04/win11React_CN#22]
### 发生了什么?

不能访问呀。。。

### 如何复现这个问题

也没什么办法

### 您在什么浏览器上遇到这个问题?

Microsoft Edge

**Comment by inwinter04** [comment]
你好，请补充您是哪个链接访问不了。最好附带上截图🥶

**Comment by inwinter04** [comment]
你好，由于本项目使用的eu.org域名在国内部分地区被墙，如果遇到访问不畅请尝试使用代理访问。
当然，如果你使用vercel构建此项目并且绑定自己的域名就不需要代理访问🥰

**Comment by inwinter04** [comment]
由于本issue已经五天没有新的回复，我将会关闭本issue。若您还有问题，可以再此提交issue或者回复本issue重新激活。
