### ISSUE TITLE
怎么同时打开多个edge？

### ISSUE THREAD

**Issue by killvf** [inwinter04/win11React_CN#23]
我的需求是同时打开多个edge，并且可以控制最大化最小化和关闭

**Comment by inwinter04** [comment]
最大化最小化功能目前可以使用的哦。🤩
对于打开多个Edge，很抱歉，目前无法做到这一点，一段时间后会将这个需求提交issue给Win11React团队，期待后续的开发吧🥰

**Comment by killvf** [comment]
没事 我new了很多个edge 然后给予不同的action和id 那就可以了

**Comment by inwinter04** [comment]
> 没事 我new了很多个edge 然后给予不同的action和id 那就可以了
> 

这太酷了😎如果可以的话可以给原项目提pr来完善它🤩过段时间我也将会将提交同步到本汉化仓库🥳

**Comment by inwinter04** [comment]
因为本issue长时间没有新的回复，现已关闭。如果您还有其他问题，回复解锁😄
