### ISSUE TITLE
登入页面日期未汉化

### ISSUE THREAD

**Issue by ZigaoWang** [inwinter04/win11React_CN#27]
# 日期未汉化
## 在多个地方，日期没有完成汉化，还是英文（其中登入页面的见以下图片）
<img width="1909" alt="Screenshot 2023-08-29 at 20 46 56" src="https://github.com/inwinter04/win11React_CN/assets/102006756/c110bbe9-02da-4525-b01d-d749feafbee2">

## 每次使用Windows 11，都会看到这个画面和汉化问题

**Comment by inwinter04** [comment]
很遗憾，我无法完成此部分汉化，这会产生问题
直接汉化文本会造成显示上的错误，这似乎与日历js代码有关🤔
你可以在提交记录中看到我在这些方面所进行的尝试
https://github.com/inwinter04/win11React_CN/commit/d171ab148ca06f110c78a0d14b2f2dd794cfca08
https://github.com/inwinter04/win11React_CN/commit/60fbeff75a490e65c1285e15933ea365d416958e
