### ISSUE TITLE
[Bug]:文件管理器 人名顯示是亂碼 

### ISSUE THREAD

**Issue by HectorLee1992** [inwinter04/win11React_CN#54]
### 发生了什么?

打開文件管理器 在上面 This PC之後顯示的C:\Users\ "亂碼"，請問有辦法修嗎?

### 如何复现这个问题

打開桌面的文件管理器

### 您在什么浏览器上遇到这个问题?

Chrome

**Comment by HectorLee1992** [comment]
了解 謝謝您，可惜我不太熟js，研究了一下也沒看到編碼在哪塊。

**Comment by inwinter04** [comment]
> 了解 謝謝您，可惜我不太熟js，研究了一下也沒看到編碼在哪塊。
> 

正是因为没有对中文编码的支持，所以很多地方才会出现奇怪的Bug😂
